import type { WorkflowDiagramSpec } from '@/lib/workflow-diagram';

export const loanLifecycleWorkflow: WorkflowDiagramSpec = {
  id: 'loan-lifecycle-workflow',
  title: 'LoanApplication workflow graph',
  subtitle: 'Entity workflow',
  entityName: 'LoanApplication',
  description:
    'Loan origination and servicing as one workflow, including document rework, KYC, underwriting, offer acceptance, arrears, restructuring, settlement, and terminal outcomes.',
  lanes: [
    {
      id: 'intakeReview',
      title: 'INTAKE & REVIEW',
      description: 'Attached processors and checks that support the main lifecycle.',
      order: 1,
      tone: 'muted',
    },
    {
      id: 'mainLifecycle',
      title: 'MAIN LIFECYCLE',
      description: 'Criteria-driven origination states from submission to offer.',
      order: 2,
      tone: 'primary',
      layout: { containsMainBaseline: true },
    },
    {
      id: 'offerServicing',
      title: 'OFFER & SERVICING',
      description: 'Accepted offers continue into active servicing, arrears, restructure, settlement, or default.',
      order: 3,
      tone: 'default',
    },
    {
      id: 'documentsRework',
      title: 'DOCUMENTS & REWORK',
      description: 'Missing documents, manual review, and terminal decline or expiry paths.',
      order: 4,
      tone: 'warning',
    },
  ],
  nodes: [
    { id: 'requestDocuments', kind: 'process', laneId: 'intakeReview', title: 'Request documents', subtitle: 'KYC · income · ID', size: 'compact', layout: { order: 1, alignXWith: 'docsComplete' } },
    { id: 'runKycChecks', kind: 'process', laneId: 'intakeReview', title: 'Run KYC checks', subtitle: 'Sanctions · PEP', size: 'compact', layout: { order: 2, alignXWith: 'kycCheck' } },
    { id: 'runUnderwriting', kind: 'process', laneId: 'intakeReview', title: 'Run underwriting', subtitle: 'Credit · affordability', size: 'compact', layout: { order: 3, alignXWith: 'underwriting' } },
    { id: 'issueOffer', kind: 'process', laneId: 'intakeReview', title: 'Issue offer', subtitle: 'Terms · APR · letter', size: 'compact', layout: { order: 4, alignXWith: 'offerIssued' } },
    { id: 'startServicing', kind: 'process', laneId: 'intakeReview', title: 'Start servicing', subtitle: 'Schedule · direct debit', size: 'compact', layout: { order: 5, alignXWith: 'activeLoan' } },

    { id: 'submitted', kind: 'state', laneId: 'mainLifecycle', title: 'Submitted', subtitle: 'Entity created', size: 'standard', tone: 'default', layout: { baseline: true, row: 'main-baseline', order: 1 } },
    { id: 'docsComplete', kind: 'decision', laneId: 'mainLifecycle', title: 'Docs complete?', size: 'decision', layout: { baseline: true, row: 'main-baseline', order: 2 } },
    { id: 'kycCheck', kind: 'state', laneId: 'mainLifecycle', title: 'KYC check', subtitle: 'Active', size: 'standard', tone: 'active', layout: { baseline: true, row: 'main-baseline', order: 3 } },
    { id: 'kycPassed', kind: 'decision', laneId: 'mainLifecycle', title: 'KYC passed?', size: 'decision', layout: { baseline: true, row: 'main-baseline', order: 4 } },
    { id: 'underwriting', kind: 'state', laneId: 'mainLifecycle', title: 'Underwriting', subtitle: 'Model + review', size: 'standard', layout: { baseline: true, row: 'main-baseline', order: 5 } },
    { id: 'creditMet', kind: 'decision', laneId: 'mainLifecycle', title: 'Credit met?', size: 'decision', layout: { baseline: true, row: 'main-baseline', order: 6 } },
    { id: 'offerIssued', kind: 'state', laneId: 'mainLifecycle', title: 'Offer issued', subtitle: 'Awaiting borrower', size: 'standard', layout: { baseline: true, row: 'main-baseline', order: 7 } },

    { id: 'offerAccepted', kind: 'decision', laneId: 'offerServicing', title: 'Offer accepted?', size: 'decision', layout: { row: 'acceptance', order: 1, alignXWith: 'offerIssued' } },
    { id: 'activeLoan', kind: 'state', laneId: 'offerServicing', title: 'Active loan', subtitle: 'Servicing', size: 'standard', layout: { row: 'servicing', order: 2, alignXWith: 'underwriting' } },
    { id: 'paymentMissed', kind: 'decision', laneId: 'offerServicing', title: 'Payment missed?', size: 'decision', layout: { row: 'servicing', order: 3, alignXWith: 'creditMet' } },
    { id: 'settled', kind: 'terminal', laneId: 'offerServicing', title: 'Settled', subtitle: 'Terminal · paid', size: 'terminal', tone: 'success', layout: { row: 'servicing', order: 4, alignXWith: 'offerIssued' } },
    { id: 'arrears', kind: 'state', laneId: 'offerServicing', title: 'Arrears', subtitle: 'Collections', size: 'standard', tone: 'warning', layout: { row: 'collections', order: 5, alignXWith: 'paymentMissed' } },
    { id: 'restructured', kind: 'state', laneId: 'offerServicing', title: 'Restructured', subtitle: 'New terms', size: 'standard', layout: { row: 'collections', order: 6, alignXWith: 'settled' } },
    { id: 'defaulted', kind: 'terminal', laneId: 'documentsRework', title: 'Defaulted', subtitle: 'Terminal', size: 'terminal', tone: 'danger', layout: { row: 'default-terminal', order: 6, alignXWith: 'paymentMissed' } },

    { id: 'manualReview', kind: 'state', laneId: 'documentsRework', title: 'Manual review', subtitle: 'Ops queue', size: 'standard', tone: 'human', layout: { row: 'review', order: 3, alignXWith: 'kycPassed' } },
    { id: 'declined', kind: 'terminal', laneId: 'documentsRework', title: 'Declined', subtitle: 'Terminal', size: 'terminal', tone: 'danger', layout: { row: 'review', order: 4, alignXWith: 'underwriting' } },
    { id: 'offerExpired', kind: 'terminal', laneId: 'documentsRework', title: 'Offer expired', subtitle: 'Terminal', size: 'terminal', tone: 'danger', layout: { row: 'review', order: 5, alignXWith: 'offerIssued' } },
    { id: 'documentsRequested', kind: 'state', laneId: 'documentsRework', title: 'Documents requested', subtitle: 'Pending borrower', size: 'wide', tone: 'warning', layout: { row: 'documents', order: 1, alignXWith: 'docsComplete' } },
    { id: 'resubmitted', kind: 'state', laneId: 'documentsRework', title: 'Resubmitted', subtitle: 'Ready to re-check', size: 'standard', layout: { row: 'documents', order: 2, alignXWith: 'kycCheck' } },
  ],
  edges: [
    { id: 'submittedToDocs', from: 'submitted', to: 'docsComplete', kind: 'main', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'docsToKyc', from: 'docsComplete', to: 'kycCheck', kind: 'main', label: 'complete', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'kycToPassed', from: 'kycCheck', to: 'kycPassed', kind: 'main', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'passedToUnderwriting', from: 'kycPassed', to: 'underwriting', kind: 'main', label: 'passed', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'underwritingToCredit', from: 'underwriting', to: 'creditMet', kind: 'main', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'creditToOffer', from: 'creditMet', to: 'offerIssued', kind: 'main', label: 'approved', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'offerToAccepted', from: 'offerIssued', to: 'offerAccepted', kind: 'main', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'acceptedToActive', from: 'offerAccepted', to: 'activeLoan', kind: 'main', label: 'accept', layout: { routing: 'orthogonal', fromPort: 'left', toPort: 'right' } },
    { id: 'activeToPayment', from: 'activeLoan', to: 'paymentMissed', kind: 'main', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'paymentToSettled', from: 'paymentMissed', to: 'settled', kind: 'main', label: 'no missed payment', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'paymentToArrears', from: 'paymentMissed', to: 'arrears', kind: 'exception', label: 'missed', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'arrearsToRestructured', from: 'arrears', to: 'restructured', kind: 'branch', label: 'cure', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'restructuredToActive', from: 'restructured', to: 'activeLoan', kind: 'loop', label: 'resume servicing', layout: { routing: 'loop-left', fromPort: 'left', toPort: 'bottom' } },
    { id: 'arrearsToDefaulted', from: 'arrears', to: 'defaulted', kind: 'exception', label: 'default', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'docsMissing', from: 'docsComplete', to: 'documentsRequested', kind: 'exception', label: 'docs missing', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'documentsToResubmitted', from: 'documentsRequested', to: 'resubmitted', kind: 'branch', label: 'resubmit', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'resubmittedToKyc', from: 'resubmitted', to: 'kycCheck', kind: 'loop', label: 're-enter KYC', layout: { routing: 'loop-left', fromPort: 'top', toPort: 'bottom' } },
    { id: 'kycManualReview', from: 'kycPassed', to: 'manualReview', kind: 'branch', label: 'manual review', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'manualReviewResume', from: 'manualReview', to: 'kycCheck', kind: 'loop', label: 'resume', layout: { routing: 'loop-left', fromPort: 'left', toPort: 'bottom' } },
    { id: 'manualReviewDecline', from: 'manualReview', to: 'declined', kind: 'exception', label: 'reject', layout: { routing: 'horizontal', fromPort: 'right', toPort: 'left' } },
    { id: 'creditDecline', from: 'creditMet', to: 'declined', kind: 'exception', label: 'criteria not met', layout: { routing: 'right-detour', fromPort: 'top', toPort: 'right' } },
    { id: 'offerExpires', from: 'offerAccepted', to: 'offerExpired', kind: 'exception', label: 'expires', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'requestDocumentsToDocs', from: 'requestDocuments', to: 'documentsRequested', kind: 'annotation', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'runKycToKyc', from: 'runKycChecks', to: 'kycCheck', kind: 'annotation', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'runUnderwritingToUnderwriting', from: 'runUnderwriting', to: 'underwriting', kind: 'annotation', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'issueOfferToOffer', from: 'issueOffer', to: 'offerIssued', kind: 'annotation', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
    { id: 'startServicingToActive', from: 'startServicing', to: 'activeLoan', kind: 'annotation', layout: { routing: 'vertical', fromPort: 'bottom', toPort: 'top' } },
  ],
  layout: {
    mainLaneId: 'mainLifecycle',
    mainNodeIds: ['submitted', 'docsComplete', 'kycCheck', 'kycPassed', 'underwriting', 'creditMet', 'offerIssued'],
    nodeGap: 34,
    rowGap: 28,
    minWidth: 1040,
  },
};

export default loanLifecycleWorkflow;
